-- 既存4サイト統合分のコンテンツテーブルを作成する
-- (grammar_points / words / sentences / conversations / conversation_lines)
--
-- 注意: id列はCSV一括インポート時にJSON側で採番した値をそのまま使うため、
-- serial/identityではなくplainなinteger primary keyにしている。
-- 将来アプリ側から新規行をINSERTする運用が始まる場合は、
-- ALTER TABLE ... ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
-- + シーケンスの開始値をmax(id)+1に設定する対応が別途必要。

create table if not exists grammar_points (
  id integer primary key,
  hsk_level integer not null,
  label text not null,
  explanation text,
  source_site text,
  created_at timestamptz not null default now()
);

create table if not exists words (
  id integer primary key,
  hanzi text not null,
  pinyin text,
  meaning_ja text,
  hsk_level integer,
  source_site text,
  created_at timestamptz not null default now()
);

create table if not exists sentences (
  id integer primary key,
  hsk_level integer not null,
  hanzi text not null,
  pinyin text,
  meaning_ja text,
  explanation_ja text,
  grammar_point_id integer references grammar_points(id),
  grammar_label_raw text,
  source_site text,
  source_id integer,
  created_at timestamptz not null default now()
);

create table if not exists conversations (
  id integer primary key,
  hsk_level integer not null,
  title text not null,
  characters jsonb,
  grammar_label_raw text,
  source_site text,
  created_at timestamptz not null default now()
);

create table if not exists conversation_lines (
  id integer primary key,
  conversation_id integer not null references conversations(id),
  line_order integer not null,
  speaker text,
  hanzi text not null,
  pinyin text,
  meaning_ja text,
  segs jsonb,
  source_site text,
  created_at timestamptz not null default now()
);

-- RLS: 学習コンテンツは全ユーザーが閲覧できればよく、書き込みは
-- アプリ側からは行わない(将来のコンテンツ管理機能・管理者操作のみ)ため、
-- SELECTのみを許可するポリシーにする。

alter table grammar_points enable row level security;
alter table words enable row level security;
alter table sentences enable row level security;
alter table conversations enable row level security;
alter table conversation_lines enable row level security;

drop policy if exists "grammar_points are viewable by everyone" on grammar_points;
create policy "grammar_points are viewable by everyone"
  on grammar_points for select
  using (true);

drop policy if exists "words are viewable by everyone" on words;
create policy "words are viewable by everyone"
  on words for select
  using (true);

drop policy if exists "sentences are viewable by everyone" on sentences;
create policy "sentences are viewable by everyone"
  on sentences for select
  using (true);

drop policy if exists "conversations are viewable by everyone" on conversations;
create policy "conversations are viewable by everyone"
  on conversations for select
  using (true);

drop policy if exists "conversation_lines are viewable by everyone" on conversation_lines;
create policy "conversation_lines are viewable by everyone"
  on conversation_lines for select
  using (true);
